### PR TITLE
[REVIEW] Add Series.from_pandas() method

### PR DESCRIPTION
**Pull request by shwina**
Adds `Series.from_pandas()` method and test. Addresses #260

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by mrocklin** [comment]
Note that I also have a solution for this in #262 (though no telling when that would be merged)

**Comment by scopatz** [comment]
Yeah, #262 seems to be the better fix here.  Also this did not run on gpuCI

**Comment by shwina** [comment]
Agreed. Closing!

**Pull request closed without merging**
