### PR TITLE
[REVIEW] Fix TravisCI build errors

### LINKED ISSUE #168: TravisCI builds failing due to too many arguments to conda build command
Looks like conda build updated and the way we've been passing the arguments no longer works.

LibGDF Issue: https://github.com/gpuopenanalytics/libgdf/issues/78

### PR DESCRIPTION
**Pull request by kkraus14**
WIP PR to fix #168

### CODE REVIEW

**Comment by kkraus14** [comment]
@scopatz this is ready for review if you wouldn't mind, should be a quick one 😄

**Comment by mike-wendt** [comment]
LGTM and will fix the upload issues for the past week, thanks @kkraus14

**Comment by kkraus14** [comment]
Thanks @mike-wendt will merge now.

**Comment by scopatz** [comment]
LGTM!

**Pull request merged**
