### PR TITLE
[Review] Remove multiple series creation during sanitize columns, resolves issue 230

### PR DESCRIPTION
**Pull request by ayushdg**
- Remove return variable from `_sanitize_columns`.
- Remove nested call of `_sanitize_values` within `_sanitize_columns` for memory efficiency 
- w.r.t issue #230

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by kkraus14** [comment]
add to whitelist

**Comment by dantegd** [comment]
Changes look good to me, @ayushdg you checked that issue 230 is no longer a problem with Titan V, right? I checked with GV100 now and it seems fine

**Comment by ayushdg** [comment]
@dantegd, Yeah I did verify that #230 is not an issue with a Titan V.

**Pull request merged**
