### PR TITLE
[WIP] Update groupby API to allow running against empty dataframes

### PR DESCRIPTION
**Pull request by kkraus14**

### CODE REVIEW

**Comment by kkraus14** [comment]
Could definitely use some tests added, but this is needed for dask_gdf's groupby to work as expected.

**Comment by kkraus14** [comment]
Will add tests in a separate PR as the groupby tests need a revamping with new "sort" and "hash" methods.

**Comment by kkraus14** [comment]
This may end up being changed in the libgdf implementation instead of at the API level with PyGDF.

**Comment by kkraus14** [comment]
rerun tests

**Comment by scopatz** [comment]
> Will add tests in a separate PR as the groupby tests need a revamping with new "sort" and "hash" methods.

Sounds good.  Looks good otherwise.

**Comment by kkraus14** [comment]
Closing because this was implemented in libgdf.

**Pull request closed without merging**
