### PR TITLE
[WIP] Modification for categorical column joins to resolve issue 166. Being tested.

### PR DESCRIPTION
**Pull request by dantegd**
Corrections for issue 164: https://github.com/gpuopenanalytics/pygdf/issues/164. Works on test case, but needs more testing to see if categories are set correctly:

```
df_left = pd.DataFrame()
nelem = 3
df_left['key1'] = np.random.randint(0, 3, nelem)
df_left['key2'] = np.random.randint(0, 5, nelem)
df_left['val1'] = np.random.randint(0, 5, nelem)
df_left['val2'] = ['a' if i%2 == 0 else 'b'for i in range(nelem)]
df_left['val1'] = df_left['val1'].astype('category')
df_left['val2'] = df_left['val2'].astype('category')


df_right = pd.DataFrame()
df_right['key1'] = np.random.randint(0, 3, nelem)
df_right['key2'] = np.random.randint(0, 5, nelem)

df_right['val1'] = np.arange(nelem)
df_right['val1'] = df_right['val1'].astype("category")
df_right['val2'] = ['a' if i%2 == 0 else 'b'for i in range(nelem)]
df_right['val2'] = df_right['val2'].astype("category")
gdf_left = DataFrame.from_pandas(df_left)
gdf_right = DataFrame.from_pandas(df_right)

cols =['val1','val2']
join_gdf = gdf_left.merge(gdf_right, on=cols, how='left')
join_gdf
```

Result: 

```
   val1 val2 key1_x key2_x key1_y key2_y
 0    4    a      0      1      1      4
 1    3    b      1      0      0      4
 2    1    a      2      3              
 3    2    b      1      4              
 4    4    b      0      2              
 5    3    a      1      1              
 6    4    b      1      1              
 7    3    a      2      0              
 8    3    a      1      3              
 9    0    b      2      2   

```

### CODE REVIEW

**Comment by Nanthini10** [comment]
I tested this on a larger data frame as a part of a workflow, and it worked without a problem.

**Comment by scopatz** [comment]
Thanks for putting this in @dantegd! Can you please add the test you posted to the test suite? Thanks!

**Comment by kkraus14** [comment]
@dantegd looks good minus the test you posted above being added to the test suite 😄

**Comment by kkraus14** [comment]
@dantegd Given we just reworked the join API entirely is this now deprecated? Can we close this?

**Comment by dantegd** [comment]
@kkraus14 with the new join and your PR using arrow it is now not needed, so closing.

**Pull request closed without merging**
