### PR TITLE
New Notebook for pymapd; h2ogpuml and MapD storage support

### PR DESCRIPTION
**Pull request by wamsiv**
The new notebook connection consists of:

- [ ] Added support for connection setup using `pymapd`

- [ ] New script for using `h2ogpuml` for training and predictions

- [ ] Optional: storing predictions back in `mapd db`.

### CODE REVIEW

**Comment by sklam** [comment]
Can pymapd be used to store back the predictions instead of using thrift?

**Comment by TomAugspurger** [comment]
> Can pymapd be used to store back the predictions instead of using thrift?

I think `con.load_table` should be able to handle that.

**Comment by TomAugspurger** [comment]
At the moment it requires a list of tuples, so something like `df.itertuples(index=False)` before passing it to `load_table`.

**Comment by sklam** [comment]
In the notebook, variable `write` can be remove since it is not used anywhere beside the check below:

```python
    if write == 0:
        os.system('rm -f rmse.txt; rm -f pred*.txt; rm -f varimp.txt; rm -f me*.txt; rm -f stats. should be removed

**Comment by wamsiv** [comment]
@sklam @TomAugspurger Made changes to the script. Please review and let me know if any issues.

**Comment by wamsiv** [comment]
@sklam Updated the notebook with `h2o4gpu` and minor additions.

**Comment by wamsiv** [comment]
@sklam Updated the notebook with h2o4gpu and minor additions.

**Comment by sklam** [comment]
The notebook looks good.

As I have mentioned before in other channels, I am planning to move the integrated demo notebooks into https://github.com/gpuopenanalytics/demo-docker/tree/master/notebook-demo-docker/demo/notebooks.   Do you want me to merge this PR and then move it over?  Or, do you want to make a PR against https://github.com/gpuopenanalytics/demo-docker instead?  

Also, I am wondering about your setup.  What version of mapd are you using?

**Comment by wamsiv** [comment]
@sklam I have created a pull request against the demo docker repo https://github.com/gpuopenanalytics/demo-docker/pull/10.
The current version of mapd which I am using is `3.2.2`

**Comment by sklam** [comment]
Closing this issue since https://github.com/gpuopenanalytics/demo-docker/pull/10 is merged.

**Pull request closed without merging**
