### PR TITLE
[REVIEW] Changes to allow numeric column names

### PR DESCRIPTION
**Pull request by dantegd**
Solution to issue 166: https://github.com/gpuopenanalytics/pygdf/issues/166

### CODE REVIEW

**Comment by scopatz** [comment]
LGTM, but is there a test that you can add for this? Or is this already covered by the test suite in some way?

**Comment by dantegd** [comment]
Added tests for accessing the columns with string and numeric names, can extend this test for other types of names. So will add the tests to the list PR (#172 ) once this one is merged :)

**Comment by scopatz** [comment]
Thanks for adding the tests! This should be good to go in now.

**Comment by kkraus14** [comment]
Thanks @dantegd, merging!

**Pull request merged**
