### PR TITLE
[WIP] Binding for libgdf CSV reader

### PR DESCRIPTION
**Pull request by sklam**
- [x] Basic test is working.
- [x] Issue with deallocation.  CSV column output is not being freed.
- [ ] Issue with invalid valid-mask from libgdf.  Currently assuming all rows are valid.

### CODE REVIEW

**Comment by mike-wendt** [comment]
run tests

**Comment by scopatz** [comment]
LGTM, but the tests are failing with a flake issue:

> ./pygdf/tests/test_column.py:1:1: F401 'itertools.product' imported but unused

And then on gpuCI it couldn't actually find the `read_csv()` function which indicates that it isn't on master libgdf to me.

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Comment by scopatz** [comment]
@sklam - this branch now has conflicts

**Comment by mike-wendt** [comment]
rerun tests

**Comment by sklam** [comment]
Closing since libgdf CSV PR is closed.  https://github.com/gpuopenanalytics/libgdf/pull/82.  Should reopen when CSV feature lands in libgdf.

**Pull request closed without merging**
